name: basic_flutter_helper
description: "A simple flutter package with common utilities as extensions/mixins/helpers"
version: 0.0.1
homepage: https://github.com/alexaniko88/basic_flutter_helper

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: 5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  mocktail: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter: